C#NET-MBDS/Back/Controllers/BackController.cs
using System;
using System.Web.Mvc;
using BO.Models;
using BO.Services;
using BO.ViewModels;

namespace BO.Controllers
{
    public class BackController : Controller
    {
        private readonly IClientService clientService;
        private readonly IPretService pretService;
        private readonly IRemboursementService remboursement;

        public BackController(IClientService clientService, IPretService pretService, IRemboursementService remboursement)
        {
            this.clientService = clientService;
            this.pretService = pretService;
            this.remboursement = remboursement;
        }

        public ActionResult Index(SearchViewModel search)
        {
            var active = Request?["active"] ?? string.Empty;
            return View(new IndexViewModel
            {
                Page = search.Page,
                Size = search.Size,
                PretConfig = new PretConfig(),
                Active = active,
                NewPrets = pretService.GetNewPrets(search.Page, search.Size),
                PretConfigs = pretService.GetPretConfigs(),
                Remboursements = remboursement.GetRembsDetail(search.Page, search.Size),
                CountPret = pretService.Count(),
                CountRembs = remboursement.Count()
            });
        }

        public ActionResult UserProfile(Guid guid)
        {
            var client = clientService.GetClient(guid);
            Console.WriteLine(client.Id);
            return View(new ClientViewModel
            {
                Client = clientService.GetClient(guid),
                Clients = clientService.GetClients()
            });
        }

        public ActionResult Sates()
        {
            var year = int.TryParse(Request["year"], out var y) ? y : 2020;
            return View("Statistiques", new StatesViewModel
            {
                Prets = pretService.GetStatePrets(year),
                Remboursements = remboursement.GetStateRembs(year),
                Interts = remboursement.GetStateInteret(year)
            });
        }

        public ActionResult Config(PretConfig config)
        {
            pretService.SavePretConfig(config);
            return RedirectToAction("Index", new {Active = "settings"});
        }
    }
}

C#NET-MBDS/Back/Views/Back/CompteClients.cshtml
@{
    ViewBag.Title = "Home Page";
}
@model BO.ViewModels.ClientViewModel

<div class="box box-solid">
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">
                <div class="card-header">
                    <h3 class="card-title">Liste client</h3>
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr style="background-color: rgba(222, 226, 230, 0.51);">
                            <th>Profile</th>
                            <th>pr&eacute;nom</th>
                            <th>Nom</th>
                            <th>Date debut</th>
                            <th>Devise</th>
                            <th>Solde</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var client in Model.Clients) {
                            <tr>
                                <td>
                                    <a href="@Url.Action("UserProfile", "Back", new {guid = client.Id})" class="nav-link">
                                        <i class="nav-icon fa fa-eye"></i>
                                    </a>
                                </td>
                                <td>@client.LastName</td>
                                <td>@client.FirstName</td>
                                <td>@client.StartDate</td>
                                <td>@client.Currency|@client.Currency</td>
                                <td>20015</td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix">
                    <ul class="pagination pagination-sm m-0 float-right">
                        <li class="page-item">
                            <a class="page-link" href="#">«</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">1</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">2</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">3</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">»</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

C#NET-MBDS/Back/Views/Back/Index.cshtml
@using BO.Extensions
@using BO.Models
@using BO.Utils
@model BO.ViewModels.IndexViewModel
@{
    var newprets = Model.NewPrets ?? new List<Pret>();
    var historiques = Model.Remboursements ?? new List<RembsDetail>();
    var configs = Model.PretConfigs ?? new List<PretConfig>();
}
<style>
    .pret-config {
        border: 1px solid #ecf0f5 !important;
        box-shadow: 0 0 0 rgba(0,0,0,0.1) !important;
    }
</style>
<div class="row">
<div class="col-md-12">
<div class="nav-tabs-custom box box-solid">
<ul class="nav nav-tabs">
    <li id="li-activity">
        <a href="#activity" data-toggle="tab">Des nouveaux prets</a>
    </li>
    <li id="li-timeline">
        <a href="#timeline" data-toggle="tab">Historiques remboursements</a>
    </li>
    <li id="li-settings">
        <a href="#settings" data-toggle="tab">Configurations pret</a>
    </li>
</ul>
<div class="tab-content">
<div class="tab-pane" id="activity">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-solid pret-config">
                <div class="box-header">
                    <h4>Recherche</h4>
                </div>
                <div class="box-body">
                    <form action="@Url.Action("Index", "Back")" method="get">
                        <input type="hidden" name="Active" value="activity"/>
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label for="clientName">Nom client</label>
                                    <input type="text" name="ClientName" class="form-control" id="clientName" placeholder="Entrer le nom client">
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label for="comptenum">N* Compte</label>
                                    <input type="text" name="NumCompte" class="form-control" id="comptenum" placeholder="Entrer le num compte">
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label for="durationid">Durations</label>
                                    <input type="number" name="Duration" class="form-control" id="durationid" placeholder="Entre un durre">
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label for="datevalueid">Date</label>
                                    <input type="date" name="Date" class="form-control" id="datevalueid" placeholder="Entrer une date">
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">Filtrer</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Liste des nouveaux prets</h3>
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr style="background-color: rgba(222, 226, 230, 0.51);">
                            <th>Details</th>
                            <th>Client</th>
                            <th>N* Compte</th>
                            <th>Dur&eacute;e</th>
                            <th>Valeurs</th>
                            <th>Debut - Fin</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var pret in newprets) {
                            var valeurs = $"{pret.Valeurs:C}";
                            var date = $"{pret.Date:d}";
                            <tr>
                                <td>
                                    <a href="#" class="nav-link">
                                        <i class="nav-icon fa fa-eye"></i>
                                    </a>
                                </td>
                                <td>@pret.Client.LastName @pret.Client.FirstName</td>
                                <td>@pret.Compte.Number</td>
                                <td>@pret.Duration @pret.PretConfig.DurationType</td>
                                <td>@valeurs</td>
                                <td>@pret.StartDate.ToString("d") &agrave; @pret.EndDate.ToString("d")</td>
                                <td>@Html.Raw(Etats.Status(pret.Etat))</td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix">
                    @Html.Paging(Model.Page, Model.Size, Model.CountPret)
                </div>
            </div>
        </div>
    </div>
</div>
<div class="tab-pane" id="timeline">
    <div class="row">
        <div class="col-md-12">
            <div class="card-header">
                <h3 class="card-title">Historiques des remboursements</h3>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                    <tr style="background-color: rgba(222, 226, 230, 0.51);">
                        <th>Profile</th>
                        <th>Client</th>
                        <th>Valeur rembours&eacute;</th>
                        <th>Total &agrave; rembours&eacute;</th>
                        <th>Date Fin</th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var histo in historiques) {
                        var dateFin = $"{histo.Pret.EndDate:d}";
                        var valeurs = $"{histo.Valeurs:C}";
                        var totalValeurs = $"{histo.TotalValues:C}";
                        <tr>
                            <td>
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fa fa-eye"></i>
                                </a>
                            </td>
                            <td>@histo.Client.FirstName @histo.Client.LastName</td>
                            <td>@valeurs</td>
                            <td>@totalValeurs</td>
                            <td>@dateFin</td>
                            <td>@Html.Raw(Etats.Status(histo.Etat))</td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
            <div class="card-footer clearfix">
                @Html.Paging(Model.Page, Model.Size, Model.CountRembs)
            </div>
        </div>
    </div>
</div>
<div class="tab-pane" id="settings">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <div class="box box-solid pret-config">
                <div class="box-header">
                    <h4>Configurations de pret</h4>
                </div>
                <div class="box-body">
                    <form action="@Url.Action("Config", "Back")" method="post" class="form-horizontal">
                        @Html.AntiForgeryToken()
                        <div class="form-group">
                            <label for="nameid" class="col-sm-3 control-label">Valeurs (%)</label>
                            <div class="col-sm-9">
                                <input type="number" name="ConfigValues" required class="form-control" id="nameid" placeholder="Valeurs">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail" class="col-sm-3 control-label">Duration min.</label>
                            <div class="col-sm-9">
                                <input type="number" name="DurationMin" required class="form-control" id="inputEmail" placeholder="Duration min.">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputExperience" class="col-sm-3 control-label">Duration max</label>
                            <div class="col-sm-9">
                                <input type="number" name="DurationMax" required class="form-control" id="inputExperience" placeholder="Duration max."/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputSkills" class="col-sm-3 control-label">Duration Type</label>
                            <div class="col-sm-9">
                                <select required class="form-control" id="inputSkills" name="DurationType">
                                    <option value="Days">Days</option>
                                    <option value="Months">Months</option>
                                    <option value="Years">Years</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-8">
                                <button type="submit" class="btn btn-danger">Save</button>
                            </div>
                        </div>
                    </form>
                    <table class="table table-bordered">
                        <thead>
                        <tr style="background-color: rgba(222, 226, 230, 0.51);">
                            <th>Action</th>
                            <th>Valeurs (%)</th>
                            <th>Duration min.</th>
                            <th>Duration max.</th>
                            <th>Duration Type</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var config in configs) {
                            var valeus = $"{config.ConfigValues:P}";
                            <tr>
                                <td>
                                    <a href="#" class="nav-link">
                                        <i class="nav-icon fa fa-edit"></i>
                                    </a>
                                </td>
                                <td>@valeus</td>
                                <td>@config.DurationMin</td>
                                <td>@config.DurationMax</td>
                                <td>@config.DurationType</td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>
</div>
</div>
</div>
</div>

C#NET-MBDS/Back/Views/Back/Statistiques.cshtml
@{
    ViewBag.Title = "Home Page";
    var prets = Model.Prets.Select(value => $"{value}");
    var rembs = Model.Remboursements.Select(value => $"{value}");
    var inters = Model.Interts.Select(value => $"{value}");
}
@model BO.ViewModels.StatesViewModel

<div class="box box-solid table-bordered">
    <div class="box-header">
        <h4>Statistiques des donn&eacute;e</h4>
        <form role="form">
            <div class="row">
                <div class="col-lg-2">
                    <div class="form-group">
                        <label for="devis">Ann&eacute;e</label>
                        <select onchange="changeYear(this.value)" required class="form-control" id="inputSkills" name="year">
                            @for (var year = 2020; year >= 2000; year--) {
                                var selected = year == (int.TryParse(Request["year"], out var y) ? y : 2020) ? "selected" : string.Empty;
                                <option @selected value="@year">@year</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="box box-solid table-bordered">
    <div class="box-header">
        <i class="fa fa-bar-chart-o"></i>
        <h3 class="box-title">Donn&eacute;es statistiques</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-default btn-sm" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <canvas id="canvas"></canvas>
    </div>
</div>

<script src="~/Content/js/Chart.min.js"></script>
<script src="~/Content/js/utils.js"></script>
<script>
	let changeYear = function(value) {
		window.location = '@Url.Action("Sates", "Back")?year='+value;
	};

	let config = {
		type: 'line',
		data: {
			labels: ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Aout', 'Septembre', 'Octobre', 'Novembre', 'Decembre'],
			datasets: [{
				label: 'Prets',
				backgroundColor: window.chartColors.red,
				borderColor: window.chartColors.red,
				fill: false,
				data: [@string.Join(", ", prets)],
			},
			{
				label: 'Remboursements',
				backgroundColor: window.chartColors.blue,
				borderColor: window.chartColors.blue,
				fill: false,
				data: [@string.Join(", ", rembs)],
			},
			{
				label: 'Interets',
				backgroundColor: window.chartColors.green,
				borderColor: window.chartColors.green,
				fill: false,
				data: [@string.Join(", ", inters)],
			}]
		},
		options: {
			responsive: true,
			title: {
				display: true,
				text: 'Statistiques interets, remboursement & prets'
			},
			scales: {
				xAxes: [{
					display: true,
				}],
				yAxes: [{
					display: true,
				}]
			}
		}
	};

	window.onload = function() {
		const ctx = document.getElementById('canvas').getContext('2d');
		window.myLine = new Chart(ctx, config);
	};
</script>

C#NET-MBDS/Back/Views/Back/UserProfile.cshtml
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header p-2">
                    <ul class="nav nav-pills">
                        <li class="nav-item">
                            <a class="nav-link active" href="#activity" data-toggle="tab">Demande pret</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#timeline" data-toggle="tab">Remboursements</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#settings" data-toggle="tab">Pret valid&eacute;</a>
                        </li>
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content">
                        <div class="active tab-pane" id="activity">
                            <div class="timeline timeline-inverse">
                                <div>
                                    <div class="timeline-item">
                                        <span class="time"><i class="far fa-clock"></i> 12:05</span>
                                        <h3 class="timeline-header"><a href="#">Support Team</a> sent you an email</h3>
                                        <div class="timeline-body">
                                            Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles,
                                        </div>
                                        <div class="timeline-footer">
                                            <a href="#" class="btn btn-primary btn-sm">Valid&eacute;</a>
                                            <a href="#" class="btn btn-danger btn-sm">Refus&eacute;</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="timeline">
                            <table class="table table-bordered table-valign-middle">
                                <thead>
                                <tr>
                                    <th style="width: 10px;">****</th>
                                    <th>Utitlisateur</th>
                                    <th>Total payé</th>
                                    <th>Reste payé</th>
                                    <th>Progression</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                        <a href="#" class="text-muted">
                                            <i class="fas fa-eye primary"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <img src="/Content/dist/img/default-150x150.png" alt="Product 1" class="img-circle img-size-32 mr-2">
                                        Some Product
                                    </td>
                                    <td>$13 USD</td>
                                    <td>$13 USD</td>
                                    <td>
                                        <small class="text-success mr-1">
                                            <i class="fas fa-arrow-up"></i>
                                            12%
                                        </small>
                                        12,000 Sold
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane" id="settings">
                            <div class="timeline timeline-inverse">
                                <div>
                                    <div class="timeline-item">
                                        <span class="time"><i class="far fa-clock"></i> 12:05</span>
                                        <h3 class="timeline-header"><a href="#">Support Team</a> sent you an email</h3>
                                        <div class="timeline-body">
                                            Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles,
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>