C#NET-MBDS/Front/Models/Base/Client.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Front.Models.Base
{
    public sealed class Client
    {
        public Guid Id { get; set; }
        [StringLength(100)]
        public string LastName { get; set; }
        [StringLength(100)]
        public string FirstName { get; set; }
        
        public DateTime? StartDate { get; set; }
        [StringLength(100)] 
        public string PassWord { get; set; }
        [StringLength(100)] 
        public string UserEmail { get; set; }
        [StringLength(50)] 
        public string Currency { get; set; }
    }
}

C#NET-MBDS/Front/Controllers/ClientController.cs
using Front.Extensions;
using Front.Models.Base;
using Front.Models.Infos;
using Front.Services;
using Microsoft.AspNetCore.Mvc;

namespace Front.Controllers
{
    public class ClientController : Controller
    {
        private readonly IClientService clientService;
        
        public ClientController(IClientService clientService)
        {
            this.clientService = clientService;
        }

        public IActionResult Login(bool error)
        {
            var session = HttpContext.Session.Get<Client>(Names.ClientSessionName);
            if (session != null)
                return RedirectToAction("Index", "Front");

            if (error) 
                ViewBag.Error = "Invalide addresse email ou mots de passe.";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ValidationLogin(LoginInfo login)
        {
            var client = clientService.LoginClient(login.UserEmail, login.PassWord);
            if (client?.Id == null)
                return RedirectToAction("Login", new {error = true});
            
            HttpContext.Session.Clear();
            HttpContext.Session.Set(Names.ClientSessionName, client);
            
            return RedirectToAction("Index", "Front");
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ValidationRegister(RegisterInfo registerInfo)
        {
            return RedirectToAction("Index", "Front");
        }

        public IActionResult Deconnexion()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }
    }
}

C#NET-MBDS/Front/Views/Client/Login.cshtml
@model Front.Models.Infos.LoginInfo
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Log in</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/Content/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/Content/plugins/icheck-bootstrap/icheck-bootstrap.css">
    <link rel="stylesheet" href="/Content/dist/css/adminlte.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="/"><b>Admin</b>LTE</a>
    </div>
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Sign in to start your session</p>
            <p class="login-box-msg" style="color: red;">@ViewBag.Error</p>
            <form asp-action="ValidationLogin" asp-controller="Client" method="post">
                @Html.AntiForgeryToken()
                <div class="input-group mb-3">
                     @Html.TextBoxFor(model=>model.UserEmail, new {@class="form-control", type="email", placeholder="Adress email"})
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    @Html.TextBoxFor(model=>model.PassWord, new {@class="form-control", type="password", placeholder="Password"})
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="remember">
                            <label for="remember">
                                Remember Me
                            </label>
                        </div>
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div>
                </div>
            </form>
            <hr/>
            <p class="mb-0">
                <a href="@Url.Action("Register", "Client")" class="text-center">Register a new membership</a>
            </p>
        </div>
    </div>
</div>
<script src="/Content/plugins/jquery/jquery.min.js"></script>
<script src="/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/Content/dist/js/adminlte.min.js"></script>
</body>
</html>

C#NET-MBDS/Front/Views/Client/Register.cshtml
@model dynamic

@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Registration Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/Content/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/Content/plugins/icheck-bootstrap/icheck-bootstrap.css">
    <link rel="stylesheet" href="/Content/dist/css/adminlte.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition register-page">
<div class="register-box">
    <div class="register-logo">
        <a href="/"><b>Admin</b>LTE</a>
    </div>
    <div class="card">
        <div class="card-body register-card-body">
            <p class="login-box-msg">Register a new membership</p>
            <form asp-controller="Client" asp-action="ValidationRegister" method="post">
                @Html.AntiForgeryToken()
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Full name">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="email" class="form-control" placeholder="Email">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" placeholder="Password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" placeholder="Retype password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="agreeTerms" name="terms" value="agree">
                            <label for="agreeTerms">
                                I agree to the <a href="#">terms</a>
                            </label>
                        </div>
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
                    </div>
                </div>
            </form>
            <hr/>
            <a href="@Url.Action("Login", "Client")" class="text-center">I already have a membership</a>
        </div>
    </div>
</div>
<script src="/Content/plugins/jquery/jquery.min.js"></script>
<script src="/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/Content/dist/js/adminlte.min.js"></script>
</body>
</html>